# docker-compose.yml to define and run the Ruwad Group website container.

# Specify the Docker Compose file format version.
version: '3.8'

# Define the services (containers) that make up your app.
services:
  # Define a service named 'ruwad-website'.
  ruwad-website:
    # Instruct Docker Compose to build the image from the Dockerfile
    # in the current directory ('.').
    build: .
    # Give the running container a specific, memorable name.
    container_name: ruwad-app
    # Map port 80 on the host machine (your server) to port 3007
    # inside the container. This lets users access the site without a port number.
    ports:
      - "80:7001"
    # Set a restart policy. 'unless-stopped' ensures the container
    # restarts automatically if it crashes or the server reboots.
    restart: unless-stopped